### ISSUE TITLE
Can you divide the shader to ultra version, high version, normal version, and low version, please?

### ISSUE THREAD

**Issue by hodakova** [Mcbamboo/bicubic-shaders-be#15]

**Comment by Darthveder69420** [comment]
Nah he change it and wants to focus on 1 version instead of multiple different versions which is only making ultra and adding an option to disable clouds. It’s probably for the best. I say don’t use a shader at all if you have a bad device. Vanilla minecraft does not look bad and there are texture packs that make it look better.
